services:
  - type: web
    name: philip-kaloki-2027
    runtime: node
    buildCommand: npm ci --include=dev && npm run build
    startCommand: npm run api
    envVars:
      - key: NODE_VERSION
        value: 22
      - key: NODE_ENV
        value: production
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_SECRET_KEY
        sync: false
      - key: ADMIN_KEY
        sync: false
